#!/usr/bin/env python3
"""
Bandit Wargame Helper & Auto-Connector
Automates SSH connections to OverTheWire Bandit levels, manages progress and passwords.
"""

import sys
import os
import json
import subprocess
import shutil

# Enable ANSI escape sequence processing on Windows
os.system('')

HOST = "bandit.labs.overthewire.org"
PORT = "2220"
DATA_FILE = "bandit_progress.json"
PASSWORDS_FILE = "passwords.txt"

# ANSI Colors
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    RESET = '\033[0m'
    DIM = '\033[2m'


def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')


def copy_to_clipboard(text: str) -> bool:
    """Copy text to system clipboard (Windows clip / macOS pbcopy / Linux xclip, xsel, wl-copy)."""
    if not text:
        return False
    try:
        if os.name == 'nt':
            subprocess.run(["clip"], input=text.strip().encode('utf-8'), check=True)
            return True
        elif sys.platform == 'darwin':
            subprocess.run(["pbcopy"], input=text.strip().encode('utf-8'), check=True)
            return True
        elif shutil.which("xclip"):
            subprocess.run(["xclip", "-selection", "clipboard"], input=text.strip().encode('utf-8'), check=True)
            return True
        elif shutil.which("xsel"):
            subprocess.run(["xsel", "--clipboard", "--input"], input=text.strip().encode('utf-8'), check=True)
            return True
        elif shutil.which("wl-copy"):
            subprocess.run(["wl-copy"], input=text.strip().encode('utf-8'), check=True)
            return True
    except Exception:
        pass
    return False


def load_data():
    default_data = {
        "current_level": 0,
        "passwords": {
            "0": "bandit0"
        }
    }
    if os.path.exists(DATA_FILE):
        try:
            with open(DATA_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
                if "passwords" not in data:
                    data["passwords"] = {"0": "bandit0"}
                if "0" not in data["passwords"]:
                    data["passwords"]["0"] = "bandit0"
                if "current_level" not in data:
                    data["current_level"] = 0
                return data
        except Exception as e:
            print(f"{Colors.RED}Warning: Could not load {DATA_FILE}: {e}{Colors.RESET}")
    return default_data


def save_data(data):
    try:
        with open(DATA_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
        
        # Also write human-readable passwords.txt
        with open(PASSWORDS_FILE, "w", encoding="utf-8") as f:
            f.write("# OverTheWire Bandit Saved Passwords\n")
            f.write("# Generated by Bandit Helper\n\n")
            sorted_levels = sorted(data["passwords"].keys(), key=lambda x: int(x) if x.isdigit() else 999)
            for lvl in sorted_levels:
                f.write(f"Level {lvl} (bandit{lvl}): {data['passwords'][lvl]}\n")
    except Exception as e:
        print(f"{Colors.RED}Error saving progress: {e}{Colors.RESET}")


def print_banner():
    banner = f"""{Colors.CYAN}{Colors.BOLD}
  ╔═════════════════════════════════════════════════════════════╗
  ║                OverTheWire - Bandit Helper                  ║
  ║               Automated SSH & Password Vault                ║
  ╚═════════════════════════════════════════════════════════════╝{Colors.RESET}"""
    print(banner)


def view_passwords(data):
    clear_screen()
    print_banner()
    print(f"\n{Colors.BOLD}=== Saved Passwords ==={Colors.RESET}\n")
    passwords = data.get("passwords", {})
    if not passwords:
        print(f"{Colors.DIM}No passwords saved yet.{Colors.RESET}")
    else:
        sorted_keys = sorted(passwords.keys(), key=lambda x: int(x) if x.isdigit() else 999)
        for k in sorted_keys:
            current_tag = f" {Colors.GREEN}◄ [Current]{Colors.RESET}" if str(data.get("current_level")) == str(k) else ""
            print(f"  {Colors.BOLD}bandit{k:<3}{Colors.RESET} : {Colors.YELLOW}{passwords[k]}{Colors.RESET}{current_tag}")
    print("\n" + "-" * 55)
    input(f"\nPress {Colors.BOLD}[Enter]{Colors.RESET} to return to main menu...")


def manual_password_entry(data):
    clear_screen()
    print_banner()
    print(f"\n{Colors.BOLD}=== Manual Password Update ==={Colors.RESET}\n")
    lvl_input = input("Enter level number (e.g., 0, 1, 2) [or press Enter to cancel]: ").strip()
    if not lvl_input:
        return
    if not lvl_input.isdigit():
        print(f"{Colors.RED}Invalid level number.{Colors.RESET}")
        input("Press Enter to continue...")
        return
    
    current_pwd = data["passwords"].get(lvl_input, "(none)")
    print(f"Current password for bandit{lvl_input}: {Colors.YELLOW}{current_pwd}{Colors.RESET}")
    new_pwd = input(f"Enter new password for bandit{lvl_input}: ").strip()
    if new_pwd:
        data["passwords"][lvl_input] = new_pwd
        save_data(data)
        print(f"{Colors.GREEN}Password for bandit{lvl_input} saved successfully!{Colors.RESET}")
    else:
        print(f"{Colors.DIM}No changes made.{Colors.RESET}")
    input("Press Enter to continue...")


def select_level(data):
    clear_screen()
    print_banner()
    print(f"\n{Colors.BOLD}=== Select Target Level ==={Colors.RESET}\n")
    print(f"Current Level: {Colors.GREEN}{data['current_level']}{Colors.RESET}")
    lvl_input = input("\nEnter level number to switch to [or Enter to keep current]: ").strip()
    if not lvl_input:
        return
    if not lvl_input.isdigit():
        print(f"{Colors.RED}Invalid level number.{Colors.RESET}")
        input("Press Enter to continue...")
        return
    
    level = int(lvl_input)
    data["current_level"] = level
    save_data(data)
    print(f"{Colors.GREEN}Active level set to bandit{level}!{Colors.RESET}")
    input("Press Enter to continue...")


def connect_ssh(level: int, data: dict):
    """
    Connects to the given level via SSH.
    Copies password to clipboard beforehand if known.
    """
    user = f"bandit{level}"
    password = data.get("passwords", {}).get(str(level), "")

    clear_screen()
    print_banner()
    print(f"\n{Colors.BOLD}Connecting to:{Colors.RESET} {Colors.CYAN}{user}@{HOST}:{PORT}{Colors.RESET}")
    
    if password:
        copied = copy_to_clipboard(password)
        print(f"{Colors.BOLD}Password:{Colors.RESET} {Colors.YELLOW}{Colors.BOLD}{password}{Colors.RESET}")
        if copied:
            print(f"{Colors.GREEN}✓ Password copied to clipboard! Just paste it (Right-Click or Ctrl+Shift+V / Ctrl+V).{Colors.RESET}")
        else:
            print(f"{Colors.DIM}(Tip: Copy the password above and paste when prompted){Colors.RESET}")
    else:
        print(f"{Colors.YELLOW}No saved password found for {user}. Enter it when prompted.{Colors.RESET}")

    print("\n" + "=" * 60)
    print(f"{Colors.DIM}Starting SSH session... Type 'exit' inside the remote shell when finished.{Colors.RESET}")
    print("=" * 60 + "\n")

    cmd = ["ssh", "-p", PORT, f"{user}@{HOST}"]
    try:
        # Launch SSH with direct terminal inheritance
        subprocess.run(cmd)
    except FileNotFoundError:
        print(f"\n{Colors.RED}Error: 'ssh' command not found. Please ensure OpenSSH is installed.{Colors.RESET}")
        input("Press Enter to continue...")
        return
    except KeyboardInterrupt:
        pass

    print("\n" + "=" * 60)
    print(f"{Colors.CYAN}SSH session for {user} closed.{Colors.RESET}")
    print("=" * 60 + "\n")


def play_loop(data):
    """
    Main progression loop: connects, asks for next password, and advances.
    """
    while True:
        level = data["current_level"]
        connect_ssh(level, data)

        next_level = level + 1
        print(f"\n{Colors.BOLD}Post-Session Actions:{Colors.RESET}")
        print(f"[{Colors.GREEN}1{Colors.RESET}] I found the password for {Colors.BOLD}bandit{next_level}{Colors.RESET} (Advance level)")
        print(f"[{Colors.CYAN}2{Colors.RESET}] Reconnect to current level ({Colors.BOLD}bandit{level}{Colors.RESET})")
        print(f"[{Colors.YELLOW}3{Colors.RESET}] Update password for current level ({Colors.BOLD}bandit{level}{Colors.RESET})")
        print(f"[{Colors.BLUE}4{Colors.RESET}] Return to Main Menu")
        print(f"[{Colors.RED}0{Colors.RESET}] Exit")

        choice = input(f"\nEnter choice [{Colors.GREEN}1{Colors.RESET}/2/3/4/0] (default: 1): ").strip()
        if choice == "" or choice == "1":
            new_pwd = input(f"\n{Colors.BOLD}Enter password for bandit{next_level}{Colors.RESET}: ").strip()
            if new_pwd:
                data["passwords"][str(next_level)] = new_pwd
                data["current_level"] = next_level
                save_data(data)
                print(f"{Colors.GREEN}Saved! Advanced to bandit{next_level}.{Colors.RESET}")
                
                auto = input(f"Connect to bandit{next_level} now? [Y/n]: ").strip().lower()
                if auto in ("", "y", "yes"):
                    continue
                else:
                    break
            else:
                adv = input(f"No password entered. Advance to level {next_level} anyway? [y/N]: ").strip().lower()
                if adv in ("y", "yes"):
                    data["current_level"] = next_level
                    save_data(data)
                    continue
        elif choice == "2":
            continue
        elif choice == "3":
            new_pwd = input(f"Enter new password for bandit{level}: ").strip()
            if new_pwd:
                data["passwords"][str(level)] = new_pwd
                save_data(data)
                print(f"{Colors.GREEN}Password updated!{Colors.RESET}")
            continue
        elif choice == "4":
            break
        elif choice == "0":
            print(f"\n{Colors.GREEN}Happy hacking! Goodbye.{Colors.RESET}")
            sys.exit(0)
        else:
            print(f"{Colors.RED}Invalid option.{Colors.RESET}")


def main_menu():
    data = load_data()
    save_data(data)  # Ensure initial state files exist

    while True:
        clear_screen()
        print_banner()
        current_lvl = data.get("current_level", 0)
        curr_pwd = data.get("passwords", {}).get(str(current_lvl), "Not saved")

        print(f"\n  Current Level    : {Colors.GREEN}{Colors.BOLD}bandit{current_lvl}{Colors.RESET}")
        print(f"  Level Password   : {Colors.YELLOW}{curr_pwd}{Colors.RESET}")
        print(f"  Saved Levels     : {Colors.CYAN}{len(data.get('passwords', {}))} levels saved{Colors.RESET}")
        print("\n" + "-" * 55)
        print(f"  [{Colors.GREEN}1{Colors.RESET}] {Colors.BOLD}Connect & Play current level (bandit{current_lvl}){Colors.RESET}")
        print(f"  [{Colors.CYAN}2{Colors.RESET}] Select a different level")
        print(f"  [{Colors.YELLOW}3{Colors.RESET}] View all saved passwords")
        print(f"  [{Colors.BLUE}4{Colors.RESET}] Add or edit a password manually")
        print(f"  [{Colors.RED}5{Colors.RESET}] Reset all progress to level 0")
        print(f"  [{Colors.DIM}0{Colors.RESET}] Exit")
        print("-" * 55)

        choice = input(f"\nChoose an option [1]: ").strip()
        if choice == "" or choice == "1":
            play_loop(data)
        elif choice == "2":
            select_level(data)
        elif choice == "3":
            view_passwords(data)
        elif choice == "4":
            manual_password_entry(data)
        elif choice == "5":
            confirm = input(f"{Colors.RED}Are you sure you want to reset all progress? [y/N]: {Colors.RESET}").strip().lower()
            if confirm in ("y", "yes"):
                data = {
                    "current_level": 0,
                    "passwords": {
                        "0": "bandit0"
                    }
                }
                save_data(data)
                print(f"{Colors.GREEN}Reset complete! Starting at level 0.{Colors.RESET}")
                input("Press Enter to continue...")
        elif choice == "0":
            print(f"\n{Colors.GREEN}Happy hacking! Goodbye.{Colors.RESET}")
            break
        else:
            print(f"{Colors.RED}Invalid option.{Colors.RESET}")
            input("Press Enter to continue...")


if __name__ == "__main__":
    try:
        main_menu()
    except KeyboardInterrupt:
        print(f"\n\n{Colors.GREEN}Exiting. Good luck on Bandit!{Colors.RESET}")
        sys.exit(0)
